# d_dset_flask_backend.py
# A "boring ah ah" Flask server to provide a read-only REST API 
# for exploring assets generated by the dataset_strategizer_dag.
#
# USAGE:
# 1. Ensure you have the required packages:
#    uv pip install Flask torch torchvision safetensors Pillow matplotlib numpy
# 2. Run from your terminal:
#    uv run python d_dset_flask_backend.py --cache_root ./validation
#
# It will automatically find a free port and print its address.

import argparse
import socket
from pathlib import Path
import json
import io

from flask import Flask, jsonify, request, send_file, render_template, abort
import safetensors
import torch
from torchvision.transforms.functional import to_pil_image
import matplotlib.pyplot as plt
import matplotlib
matplotlib.use('Agg') # Use non-interactive backend for server-side plotting

# --- 1. Global State & Configuration ---
# This data will be loaded once at startup.
# The server is read-only, so this simple global state is sufficient.
API_SPEC = {}
CACHE_ROOT = None
# Maps work_id -> {asset_type: {location_str, ...}}
WORK_ID_TO_ASSETS = {}
# Maps asset_type -> list of available work_ids
ASSET_TYPE_INDEX = {}
# Maps report_name -> {file_path, metadata}
REPORTS_INDEX = {}

# --- 2. Server Setup Utilities ---

def find_free_port():
    """Finds an unused TCP port on the host."""
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.bind(('', 0))
        return s.getsockname()[1]

def scan_cache_directory(root_path: Path):
    """
    Scans the cache directory, parsing all .safetensors files to build
    the server's internal index of available assets and reports.
    """
    global WORK_ID_TO_ASSETS, ASSET_TYPE_INDEX, REPORTS_INDEX, CACHE_ROOT
    CACHE_ROOT = root_path
    print(f"[Server] Scanning cache directory: {root_path}...")

    if not root_path.is_dir():
        raise FileNotFoundError(f"Cache root directory not found: {root_path}")

    for f_path in root_path.glob("*.safetensors"):
        try:
            with safetensors.safe_open(f_path, framework="pt", device="cpu") as f:
                # Check for aggregate reports first via metadata
                metadata = f.metadata()
                if metadata and "aggregate_result" in " ".join(metadata.keys()):
                    # This is likely an aggregate report file
                    report_key = next(iter(metadata.keys()))
                    report_info = json.loads(metadata[report_key])
                    asset_type = report_info.get("asset_type")
                    if asset_type:
                        report_name = asset_type.replace("aggregate_", "").replace("_report", "")
                        REPORTS_INDEX[report_name] = {
                            "file_path": f_path,
                            "asset_type": asset_type,
                            "report_key_prefix": report_key,
                            "contributing_work_ids": report_info.get("contributing_work_ids", [])
                        }
                        print(f"  - Found Aggregate Report: '{report_name}' in {f_path.name}")
                    continue

                # Process as a regular asset cache file
                for key in f.keys():
                    parts = key.split('_')
                    if len(parts) < 2: continue
                    
                    work_id, asset_type = parts[0], "_".join(parts[1:])
                    
                    # Handle nested assets (like text embeddings)
                    if asset_type.endswith(("cond", "uncond")):
                       asset_type = "_".join(parts[1:-1]) # e.g. text_embedding
                    if asset_type.endswith(("mean", "std", "global", "channel")):
                        asset_type = "latent_stats"

                    if work_id not in WORK_ID_TO_ASSETS:
                        WORK_ID_TO_ASSETS[work_id] = {}
                    if asset_type not in ASSET_TYPE_INDEX:
                        ASSET_TYPE_INDEX[asset_type] = []

                    if asset_type not in WORK_ID_TO_ASSETS[work_id]:
                         WORK_ID_TO_ASSETS[work_id][asset_type] = {"location_file": str(f_path)}
                         ASSET_TYPE_INDEX[asset_type].append(work_id)

        except Exception as e:
            print(f"  - WARNING: Could not process file {f_path.name}. Error: {e}")
    
    print(f"[Server] Scan complete. Found {len(WORK_ID_TO_ASSETS)} unique work items.")
    print(f"         Available asset types: {list(ASSET_TYPE_INDEX.keys())}")
    print(f"         Available reports: {list(REPORTS_INDEX.keys())}")


def build_api_spec(host, port):
    """Builds the API specification dictionary."""
    global API_SPEC
    base_url = f"http://{host}:{port}"
    API_SPEC = {
        "description": "The Dataset Loupe API. A read-only service for exploring artifacts.",
        "version": "1.0.0",
        "human_interface": f"{base_url}/client",
        "endpoints": {
            "GET /": "Returns this API specification.",
            "GET /client": "Serves the interactive web UI.",
            "GET /api/summary": "Provides a high-level overview of all cached items.",
            "GET /api/item/{work_id}": "Fetches the detailed manifest for a single work item.",
            "GET /api/view/image/{work_id}/{asset_type}": "Renders a tensor as a PNG image.",
            "GET /api/reports/{report_name}": "Retrieves a pre-computed aggregate report.",
            "POST /client/action": "Receives a high-level command and returns a display plan."
        }
    }

# --- 3. Flask Application ---

app = Flask(__name__, template_folder='templates')

@app.errorhandler(404)
def resource_not_found(e):
    return jsonify(error="Not Found", message="The requested resource does not exist."), 404

@app.errorhandler(500)
def internal_server_error(e):
    return jsonify(error="Internal Server Error", message=str(e)), 500

# --- Core Endpoints ---

@app.route("/")
def get_api_spec():
    """Serves the universal map of the API."""
    return jsonify(API_SPEC)

@app.route("/client")
def serve_client():
    """Serves the human-facing web client."""
    return render_template('index.html')

# --- API Endpoints ---

@app.route("/api/summary")
def get_summary():
    return jsonify({
        "work_ids": sorted(list(WORK_ID_TO_ASSETS.keys())),
        "available_asset_types": sorted(list(ASSET_TYPE_INDEX.keys())),
        "available_reports": sorted(list(REPORTS_INDEX.keys())),
        "total_items": len(WORK_ID_TO_ASSETS)
    })

@app.route("/api/item/<work_id>")
def get_item_details(work_id):
    if work_id not in WORK_ID_TO_ASSETS:
        abort(404)
    return jsonify(WORK_ID_TO_ASSETS[work_id])
    
@app.route("/api/reports/<report_name>")
def get_report(report_name):
    if report_name not in REPORTS_INDEX:
        abort(404)
    # For now, we just return the basic info. A more complex implementation
    # could parse the report file here.
    return jsonify(REPORTS_INDEX[report_name])


@app.route("/api/view/image/<work_id>/<asset_type>")
def view_image(work_id, asset_type):
    """The core visualization engine. Loads a tensor and renders it as a PNG."""
    if work_id not in WORK_ID_TO_ASSETS:
        abort(404)
    
    asset_info = WORK_ID_TO_ASSETS[work_id].get(asset_type)
    if not asset_info and asset_type != 'vae_residual':
        abort(404, description=f"Asset type '{asset_type}' not found for work_id '{work_id}'.")

    try:
        if asset_type == 'vae_residual':
            # This is a virtual asset, computed on the fly
            recon_info = WORK_ID_TO_ASSETS[work_id].get('reconstructed_image')
            # For original image, we'd need to trace it back to the source plan.
            # This is complex, so we'll stub it for now and just show the reconstruction.
            # A real implementation would need to read the `latent_encoding_work_specs`.
            if not recon_info: abort(404, description="Reconstructed image required for residual not found.")
            
            with safetensors.safe_open(recon_info['location_file'], framework="pt", device="cpu") as f:
                tensor = f.get_tensor(f"{work_id}_reconstructed_image")
            # For demo, the residual is just the reconstructed image.
            # A real version would be `original - recon`.
            tensor = (tensor - tensor.min()) / (tensor.max() - tensor.min()) # Normalize for viewing

        elif asset_type == 'latent':
            latent_info = WORK_ID_TO_ASSETS[work_id]['latent']
            with safetensors.safe_open(latent_info['location_file'], framework="pt", device="cpu") as f:
                tensor = f.get_tensor(f"{work_id}_latent")
        
        else: # Assumes a standard image-like asset
            with safetensors.safe_open(asset_info['location_file'], framework="pt", device="cpu") as f:
                tensor = f.get_tensor(f"{work_id}_{asset_type}")

        # --- Tensor to Image Conversion ---
        if tensor.dim() == 4 and tensor.shape[0] == 1: tensor = tensor.squeeze(0)
        
        img_buffer = io.BytesIO()

        if asset_type == 'latent' and tensor.dim() == 3 and tensor.shape[0] == 4:
            # Render 4 channels in a 2x2 grid
            fig, axes = plt.subplots(2, 2, figsize=(8, 8), constrained_layout=True)
            fig.suptitle(f"Latent: {work_id[:12]}...", fontsize=14)
            vmin, vmax = tensor.min(), tensor.max()
            for i, ax in enumerate(axes.flat):
                channel_data = tensor[i].float()
                ax.imshow(channel_data, cmap='viridis', vmin=vmin, vmax=vmax)
                ax.set_title(f"Ch {i} | Mean: {channel_data.mean():.2f}, Std: {channel_data.std():.2f}")
                ax.axis('off')
            fig.savefig(img_buffer, format='png')
            plt.close(fig)
        else:
            # Render as a standard image
            pil_img = to_pil_image(tensor.float().cpu())
            pil_img.save(img_buffer, format='PNG')
            
        img_buffer.seek(0)
        return send_file(img_buffer, mimetype='image/png')

    except Exception as e:
        print(f"ERROR rendering image for {work_id}/{asset_type}: {e}")
        abort(500, description="Failed to render tensor as image.")


@app.route("/client/action", methods=['POST'])
def handle_client_action():
    """The 'MCP Latch' - translates a high-level UI query into a display plan."""
    action_request = request.get_json()
    if not action_request or "action" not in action_request:
        return jsonify(error="Invalid request format"), 400

    action = action_request.get("action")
    query = action_request.get("query", {})

    if action == "view_list":
        # In a real app, we'd apply sorting/filtering from the query.
        # For now, we'll just return a plan for the first few items.
        limit = query.get("limit", 5)
        work_ids = sorted(list(WORK_ID_TO_ASSETS.keys()))[:limit]
        views_to_render = action_request.get("views_to_render", ["reconstructed_image"])

        display_plan = []
        for work_id in work_ids:
            plan_item = {"work_id": work_id, "views": {}}
            for view in views_to_render:
                if view in WORK_ID_TO_ASSETS[work_id] or view == 'vae_residual':
                    plan_item["views"][view] = f"/api/view/image/{work_id}/{view}"
            display_plan.append(plan_item)
        
        return jsonify({"display_plan": display_plan})
        
    return jsonify(error="Unknown action"), 400


# --- 4. Main Execution ---

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Dataset Loupe Backend Server")
    parser.add_argument(
        '--cache_root',
        type=Path,
        required=True,
        help="Path to the root directory containing the .safetensors cache files."
    )
    args = parser.parse_args()

    # Initialize the server state
    scan_cache_directory(args.cache_root)
    port = find_free_port()
    host = "127.0.0.1"
    
    # Finalize the spec with the runtime host/port
    build_api_spec(host, port)
    
    print("\n--- Dataset Loupe Server ---")
    print(f"Serving assets from: {args.cache_root.resolve()}")
    print(f"API specification available at: http://{host}:{port}/")
    print(f"Human-friendly client at: http://{host}:{port}/client")
    print("----------------------------")
    print("Press CTRL+C to stop the server.")

    app.run(host=host, port=port, debug=False)