# d_dset_flask_backend.py
# A "boring ah ah" Flask server to provide a read-only REST API 
# for exploring assets generated by the dataset_strategizer_dag.
#
# USAGE:
# 1. Ensure you have the required packages:
#    uv pip install Flask torch torchvision safetensors Pillow matplotlib numpy
# 2. Run from your terminal:
#    uv run python d_dset_flask_backend.py --cache_root ./validation
#
# It will automatically find a free port and print its address.

import argparse
import socket
from pathlib import Path
import json
import io

from flask import Flask, jsonify, request, send_file, render_template, abort, send_from_directory
import safetensors
import torch
from torchvision.transforms.functional import to_pil_image
import matplotlib.pyplot as plt
import matplotlib
matplotlib.use('Agg') # Use non-interactive backend for server-side plotting

# --- 1. Global State & Configuration ---
API_SPEC = {}
CACHE_ROOT = None
# Maps work_id -> {asset_key_suffix: {location_file, ...}}
WORK_ID_TO_ASSETS = {}
# Maps asset_type_suffix -> list of available work_ids
ASSET_TYPE_INDEX = {}
# Maps report_name -> list of contributing work_ids
REPORT_BASED_INDEX = {}

# --- 2. Server Setup Utilities ---

def find_free_port():
    """Finds an unused TCP port on the host."""
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.bind(('', 0))
        return s.getsockname()[1]

def scan_cache_directory(root_path: Path):
    """
    (REVISED) Scans the cache directory to build a work-item-centric index.
    This creates a WORK_ID_TO_ASSETS mapping of:
    { work_id_1: [asset_type_A, asset_type_B], ... }
    """
    global WORK_ID_TO_ASSETS, CACHE_ROOT
    CACHE_ROOT = root_path
    print(f"[Server] Scanning cache directory: {root_path}...")

    if not root_path.is_dir():
        raise FileNotFoundError(f"Cache root directory not found: {root_path}")

    # This will temporarily map work_id -> {asset_type: location}
    temp_work_id_map = {}
    # This will be our final primary index: work_id -> sorted list of asset types
    WORK_ID_TO_ASSETS = {}
    
    for f_path in root_path.glob("*.safetensors"):
        try:
            with safetensors.safe_open(f_path, framework="pt", device="cpu") as f:
                for key in f.keys():
                    parts = key.split('_', 1)
                    if len(parts) < 2: continue
                    work_id, asset_type = parts[0], parts[1]
                    
                    if work_id not in temp_work_id_map:
                        temp_work_id_map[work_id] = {}

                    # Store the location info for each asset
                    if asset_type not in temp_work_id_map[work_id]:
                        temp_work_id_map[work_id][asset_type] = {"location_file": str(f_path)}

        except Exception as e:
            print(f"  - WARNING: Could not process file {f_path.name} during asset scan. Error: {e}")
    
    # Finalize the primary WORK_ID_TO_ASSETS index with sorted asset lists
    for work_id, assets in temp_work_id_map.items():
        WORK_ID_TO_ASSETS[work_id] = sorted(list(assets.keys()))

    # Store the more detailed location map in the app's context for later use
    # This avoids making it a global, keeping WORK_ID_TO_ASSETS as the clean index.
    app.config['ASSET_LOCATION_MAP'] = temp_work_id_map

    print(f"[Server] Scan complete. Found {len(WORK_ID_TO_ASSETS)} unique work items.")

def build_api_spec(host, port):
    """
    (REVISED) Builds the API specification dictionary, replacing the legacy
    /api/view/image endpoint with the more capable /api/asset endpoint.
    """
    global API_SPEC
    base_url = f"http://{host}:{port}"
    API_SPEC = {
        "description": "The Dataset Loupe API. A read-only service for exploring artifacts.",
        "version": "4.0.0",
        "human_interface": f"{base_url}/client",
        "endpoints": {
            "GET /": "Returns this API specification.",
            "GET /client": "Serves the interactive web UI.",
            "GET /api/index": "Provides the primary, work-item-centric index of the dataset.",
            "POST /api/batch/assets": "Accepts a list of work_ids and an asset_type, and returns the data for all of them.",
            "GET /api/asset/{work_id}/{asset_type}": "Fetches a single asset, prepared as structured JSON for client-side rendering."
        }
    }

# --- 3. Flask Application ---

app = Flask(__name__, template_folder='templates')

@app.errorhandler(404)
def resource_not_found(e):
    return jsonify(error="Not Found", message="The requested resource does not exist."), 404

@app.errorhandler(500)
def internal_server_error(e):
    return jsonify(error="Internal Server Error", message=str(e)), 500

@app.route("/")
def get_api_spec():
    return jsonify(API_SPEC)

@app.route("/client")
def serve_client():
    return render_template('index.html')

# ADDED: Route to serve JS file from the templates directory.
@app.route('/templates/<path:filename>')
def serve_template_asset(filename):
    return send_from_directory('templates', filename)

@app.route("/api/indices")
def get_indices():
    return jsonify({
        "by_asset_type": ASSET_TYPE_INDEX,
        "by_report": REPORT_BASED_INDEX
    })

@app.route("/api/index")
def get_index():
    """
    Serves the primary, work-item-centric view of the dataset.
    Satisfies Rule 2.1 by its structure.
    """
    return jsonify({
        "query_endpoint": "/api/index",
        "work_items": WORK_ID_TO_ASSETS
    })

@app.route("/api/item/<work_id>")
def get_item_details(work_id):
    if work_id not in WORK_ID_TO_ASSETS:
        abort(404)
    return jsonify(WORK_ID_TO_ASSETS[work_id])

def _prepare_asset_for_transport(tensor, asset_type):
    """
    (NEW HELPER) Centralized function to inspect a tensor and convert it
    into a structured, client-friendly JSON object with a render_type hint.
    """
    # Special case: The detailed 2x2 plot for multi-channel latent tensors.
    if asset_type == 'latent' and tensor.dim() == 3 and tensor.shape[0] == 4:
        fig, axes = plt.subplots(2, 2, figsize=(8, 8), constrained_layout=True)
        vmin, vmax = tensor.min(), tensor.max()
        for i, ax in enumerate(axes.flat):
            channel_data = tensor[i].float()
            ax.imshow(channel_data, cmap='viridis', vmin=vmin, vmax=vmax)
            ax.set_title(f"Ch {i} | Mean: {channel_data.mean():.2f}, Std: {channel_data.std():.2f}")
            ax.axis('off')
        
        img_buffer = io.BytesIO()
        fig.savefig(img_buffer, format='png')
        plt.close(fig)
        b64_image = base64.b64encode(img_buffer.getvalue()).decode('utf-8')
        return {"render_type": "image", "data": b64_image}

    # General cases for other tensors.
    elif tensor.dim() >= 2: # Treat as a standard image
        if tensor.dim() == 4 and tensor.shape[0] == 1: tensor = tensor.squeeze(0)
        tensor = torch.clamp(tensor, 0, 1)
        pil_img = to_pil_image(tensor.float().cpu())
        img_buffer = io.BytesIO()
        pil_img.save(img_buffer, format='PNG')
        b64_image = base64.b64encode(img_buffer.getvalue()).decode('utf-8')
        return {"render_type": "image", "data": b64_image}

    elif tensor.dim() == 0: # Treat as a scalar value
        return {"render_type": "scalar", "data": {"value": f"{tensor.item():.4f}"}}
    
    else: # Treat as a generic vector/tensor
        return {
            "render_type": "vector", 
            "data": {
                "repr": str(tensor.tolist()),
                "shape": str(list(tensor.shape)),
                "dtype": str(tensor.dtype)
            }
        }


@app.route("/api/asset/<work_id>/<path:asset_type>")
def get_asset_details(work_id, asset_type):
    """
    Fetches a single asset and returns its structured
    JSON representation, prepared for client-side rendering.
    This endpoint replaces the legacy /api/view/image endpoint.
    """
    asset_location_map = app.config.get('ASSET_LOCATION_MAP', {})
    if work_id not in asset_location_map or asset_type not in asset_location_map[work_id]:
        abort(404, description=f"Asset '{asset_type}' not found for work_id '{work_id}'.")
    
    asset_info = asset_location_map[work_id][asset_type]
    location_file = asset_info['location_file']
    tensor_key = f"{work_id}_{asset_type}"

    try:
        with safetensors.safe_open(location_file, framework="pt", device="cpu") as f:
            tensor = f.get_tensor(tensor_key)
        
        # Use the centralized helper function to ensure consistent processing
        response_data = _prepare_asset_for_transport(tensor, asset_type)
        return jsonify(response_data)

    except Exception as e:
        print(f"ERROR preparing asset for {work_id}/{asset_type}: {e}")
        return jsonify({"render_type": "error", "data": {"message": str(e)}}), 500

@app.route("/api/batch/assets", methods=['POST'])
def get_batch_assets():
    """
    (REVISED) Serves a collection of assets, using the centralized helper
    to ensure consistent visualization logic.
    """
    request_data = request.get_json()
    if not request_data or 'work_ids' not in request_data or 'asset_type' not in request_data:
        abort(400)

    work_ids = request_data['work_ids']
    asset_type = request_data['asset_type']
    
    asset_location_map = app.config.get('ASSET_LOCATION_MAP', {})
    batch_response = {}

    for work_id in work_ids:
        if work_id not in asset_location_map or asset_type not in asset_location_map[work_id]:
            continue

        asset_info = asset_location_map[work_id][asset_type]
        location_file = asset_info['location_file']
        tensor_key = f"{work_id}_{asset_type}"

        try:
            with safetensors.safe_open(location_file, framework="pt", device="cpu") as f:
                tensor = f.get_tensor(tensor_key)
            
            # Use the new centralized helper function
            batch_response[work_id] = _prepare_asset_for_transport(tensor, asset_type)

        except Exception as e:
            print(f"ERROR preparing batch asset for {work_id}/{asset_type}: {e}")
            batch_response[work_id] = {"render_type": "error", "data": {"message": str(e)}}

    return jsonify({
        "query": { "asset_type": asset_type },
        "assets": batch_response
    })

# --- 4. Main Execution ---

if __name__ == "__main__":
    import base64
    parser = argparse.ArgumentParser(description="Dataset Loupe Backend Server")
    parser.add_argument('--cache_root', type=Path, required=True, help="Path to the cache directory.")
    args = parser.parse_args()

    scan_cache_directory(args.cache_root)
    port = find_free_port()
    host = "127.0.0.1"
    
    build_api_spec(host, port)
    
    print("\n--- Dataset Loupe Server ---")
    print(f"Serving assets from: {args.cache_root.resolve()}")
    print(f"API specification available at: http://{host}:{port}/")
    print(f"Human-friendly client at: http://{host}:{port}/client")
    print("----------------------------")

    app.run(host=host, port=port, debug=False)